adjusting yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -52,29 +52,34 @@ test_job:
     # Merge the coverage data from Communicator and Server modules
     - echo "Merging coverage data..."
     - mvn org.jacoco:jacoco-maven-plugin:merge@merge \
-      -Djacoco.destFile=target/merged-jacoco.exec \
-      -Djacoco.dataFile1=Device/Communicator/target/jacoco.exec \
-      -Djacoco.dataFile2=Server/target/jacoco.exec
+          -Djacoco.destFile=target/merged-jacoco.exec \
+          -Djacoco.dataFile1=Device/Communicator/target/jacoco.exec \
+          -Djacoco.dataFile2=Server/target/jacoco.exec || exit 1
 
     # Generate a combined JaCoCo coverage report
     - echo "Generating combined coverage report..."
     - mvn org.jacoco:jacoco-maven-plugin:report@report \
-      -Djacoco.dataFile=target/merged-jacoco.exec \
-      -DoutputDirectory=target/merged-report
+          -Djacoco.dataFile=target/merged-jacoco.exec \
+          -DoutputDirectory=target/merged-report || exit 1
 
     # Parse the combined coverage percentage from the merged XML report
     - echo "Parsing combined coverage from target/merged-report/jacoco.xml..."
     - |
-      coverageVal=$(xmllint --xpath "
-        sum(//counter[@type='INSTRUCTION']/@covered)
-        div
-        (
+      if [ -f target/merged-report/jacoco.xml ]; then
+        coverageVal=$(xmllint --xpath "
           sum(//counter[@type='INSTRUCTION']/@covered)
-          + sum(//counter[@type='INSTRUCTION']/@missed)
-        ) * 100
-      " target/merged-report/jacoco.xml)
-
-      echo "Combined Coverage: ${coverageVal}%"
+          div
+          (
+            sum(//counter[@type='INSTRUCTION']/@covered)
+            + sum(//counter[@type='INSTRUCTION']/@missed)
+          ) * 100
+        " target/merged-report/jacoco.xml || echo "Error parsing coverage XML")
+      
+        echo "Combined Coverage: ${coverageVal}%"
+      else
+        echo "Coverage report not found: target/merged-report/jacoco.xml"
+        exit 1
+      fi
 
   only:
     - main
